## Python Lists

On the numbers side, there's the `float`, to represent a real number, and the `int`, to represent an integer. Next, we also have `str`, short for string, to represent text in Python, and `bool`, which can be either True or False. You can save these values as a variable, like these examples show. Each variable then represents a single value. As a data scientist, you'll often want to work with many data points. If you for example want to measure the height of everybody in your family, and store this information in Python, it would be inconvenient to create a new python variable for each point you collected right? What you can do instead, is store all this information in a Python list.<br>
`float - real number`<br>
`int - ìnteger numbers` <br>
`str - string, text`<br>
`bool - True, False`<br>

As a data scientist,you'll often want to work with many data points. If you for example want to measure the height of everybody in your family, and store this information in Python, it would be inconvenient to create a new python variable for each point you collected right? What you can do instead, is store all this information in a Python list.

As a data scientist,you'll often want to work with many data points. If you for example want to measure the height of everybody in your family, and store this information in Python, it would be inconvenient to create a new python variable for each point you collected right? What you can do instead, is store all this information in a Python list.

You can build such a list with square brackets. Suppose you asked your two sisters and parents for their height, in meters. You can build the list as follows: Of course, also this data structure can be referenced to with a variable. Simply put the variable name and the equals sign in front, like here. A list is a way to give a single name to a collection of values. These values, or elements, can have any type; they can be floats, integer, booleans, strings, but also more advanced Python types, even lists. It's perfectly possible for a list to contain different types as well.

Suppose, for example, that you want to add the names of your sisters and parents to the list, so that you know which height belongs to who. You can throw in some strings without issues. But that's not all. I just told you that lists can also contain lists themselves. Instead of putting the strings in between the numbers, you can create little sublists for each member of the family. One for liz, one for emma and so on. Now, you can tell Python that these sublists are the elements of another list, that I named fam2: the little lists are wrapped in square brackets and separated with commas. If you now print out fam2, you see that we have a list of lists. The main list contains 4 sub-lists. We're dealing with a new Python type here, next to the strings, booleans, integers and floats you already know about:

In [4]:
# Example
fam = ["Sam", 1.78, "Carl", 1.73, "Peter", 1.55, "Ana", 1.80]

In [5]:
fam2 = [["Sam", 1.78,],
        ["Carl", 1.73], 
        ["Peter", 1.55], 
        ["Ana", 1.80]]

In [6]:
type(fam)

list

### Exercise lists
Create a list <br>
A list is a compound data type; you can group values together, like this:<br>

a = "is"<br>
b = "nice"<br>
my_list = ["my", "list", a, b]<br>
After measuring the height of your family, you decide to collect some information on the house you're living in. The areas of the different parts of your house are stored in separate variables in the exercise.

**Instrcutions** <br>
Create a list, `areas`, that contains the area of the hallway (`hall`), kitchen (`ki`), living room (`liv`), bedroom (`bed`) and bathroom (`bath`), in this order. Use the predefined variables.
Print areas with the print() function.

In [8]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas

areas = [hall, kit, liv, bed, bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


### Create lists with different types
Although it's not really common, a list can also contain a mix of Python types including strings, floats, and booleans.

You're now going to add the room names to your list, so you can easily see both the room name and size together.

Some of the code has been provided for you to get you started. Pay attention here! "bathroom"
is a string, while bath is a variable that represents the float 9.50 you specified earlier.

Finish the code that creates the areas list. Build the list so that the list first contains the name of each room as a string and then its area. In other words, add the strings "hallway", "kitchen" and "bedroom" at the appropriate locations. Print areas again; is the printout more informative this time?

In [9]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
#areas = [____, hall, ____, kit, "living room", liv, ____, bed, "bathroom", bath]

# Print areas
#____

In [10]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


**List of lists** <br>
As a data scientist, you'll often be dealing with a lot of data, and it will make sense to group some of this data.<br>

Instead of creating a list containing strings and floats, representing the names and areas of the rooms in your house, you can create a list of lists. <br>

Remember: `"hallway"` is a string, while `hall` is a variable that represents the float `11.25` you specified earlier.<br>

Finish the list of lists so that it also contains the bedroom and bathroom data. Make sure you enter these in order!
Print out house; does this way of structuring your data make more sense?

In [12]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# House information as list of lists
#house = [["hallway", hall],
#         ["kitchen", kit],
#         ["living room", liv],
#        ____,
#        ____]

# Print out house
#____

In [13]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# House information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
        ["bedroom", bed],
        ["bathroom"], bath]

# Print out house
print(house)

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom'], 9.5]


In [14]:
### Subsetting Lists

In [15]:
fam2 = ["Liz", 1.73, "emma", 1.68, "mom" , 1.72, "dad", 1.89]
print (fam2)

['Liz', 1.73, 'emma', 1.68, 'mom', 1.72, 'dad', 1.89]


Python uses the index to do this. Have a look at the fam list again here. The first element in the list has index 0, the second element has index 1, and so on. Suppose that you want to select the height of emma, the float 1.68. It's the fourth element, so it has index 3. To select it, you use 3 inside square brackets. Similarly, to select the string "dad" from the list,

In [16]:
fam2[3]

1.68

which is the seventh element in the list, you'll need to put the index 6 inside square brackets. You can also count backwards, using negative indexes. This is useful if you want to get some elements at the end of your list. To get your dad's height, for example, you'll need the index -1. These are the negative indexes for all list elements.


In [17]:
fam2[-1]

1.89

In [18]:
# or 
fam2[7]

1.89

### **List slicing** <br>
which allows you to select multiple elements from a list, thus creating a new list. You can do this by specifying a range, using a colon. Let's first have another look at the list, and then try this piece of code. Can you guess what it'll return? 

Apparently, only the elements with index 3 and 4, get returned. The element with index 5 is not included. In general, this is the syntax: the index you specify before the colon, so where the slice starts, is included, while the index you specify after the colon, where the slice ends, is not. With this in mind, can you tell what this call will return? You probably guessed correctly that this call gives you a list with three elements, corresponding to the elements with index 1, 2 and 3 of the fam list. You can also choose to just leave out the index before or after the colon.
[start : end]

In [19]:
fam2[1:4]

[1.73, 'emma', 1.68]

If you leave out the index where the slice should begin, you're telling Python to start the slice from index 0, like this example. If you leave out the index where the slice should end, you include all elements up to and including the last element in the list, like here. Now it's time to head over to the exercises,

In [20]:
fam2[:4]

['Liz', 1.73, 'emma', 1.68]

In [21]:
print(fam2)

['Liz', 1.73, 'emma', 1.68, 'mom', 1.72, 'dad', 1.89]


### Exercise

Subset and conquer
Subsetting Python lists is a piece of cake. Take the code sample below, which creates a list x and then selects "b" from it. Remember that this is the second element, so it has index 1. You can also use negative indexing.
```
x = ["a", "b", "c", "d"]
x[1]
x[-3] # same result!
```
Remember the areas list from before, containing both strings and floats? Its definition is already in the script. Can you add the correct code to do some Python subsetting?

In [23]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]


In [24]:
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [25]:
# Print out second element from areas
#print(areas[____])

# Print out last element from areas
#print(areas[____])

# Print out the area of the living room
#print(areas[____])

In [26]:
# Print out second element from areas
print(areas[1])


11.25


In [27]:
# Print out last element from areas
print(areas[9])

9.5


In [28]:
# Print out the area of the living room
print(areas[5])

20.0


### Exercise 2
**Slicing and dicing**
Selecting single values from a list is just one part of the story. It's also possible to slice your list, which means selecting multiple elements from your list. Use the following syntax:

```
my_list[start:end]
```

The `start` index will be included, while the `end` index is not. However, it's also possible not to specify these indexes. If you don't specify the `start` index, Python figures out that you want to start your slice at the beginning of your list.

1. Use slicing to create a list, downstairs, that contains the first 6 elements of areas.

In [29]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
print(areas)


['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [30]:
# Use slicing to create downstairs
#downstairs = areas[____]

downstairs = areas[:6]
print(downstairs)


['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]


In [31]:
# Use slicing to create upstairs
upstairs = areas[6:10]
print(upstairs)

['bedroom', 10.75, 'bathroom', 9.5]


### Subsetting lists of lists
A Python list can also contain other lists.

To subset lists of lists, you can use the same technique as before: square brackets. 
    This would look something like this for a list, `house`:



In [46]:
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

# Subset the house list
#house___

1. Subset the house list to get the float 9.5.



In [51]:
house[-1][1]

9.5